### ISSUE TITLE
Project-3 - test_build_nn fails with Tensorflow 1.3

### ISSUE THREAD

**Issue by xizhenke** [udacity/deep-learning#250] opened 2018-02-04 00:15 UTC
From:
https://github.com/udacity/deep-learning/issues/216
Using TF 1.3, the test_build_nn() test fails as the second dimension is not None. The same code on TF 1.1 works fine. 

AssertionError: Final state wrong shape. Found shape (2, 2, 128, 256)"

However, I am trying to run jupyter on AWS. Can anyone please tell me how to replace tensorflow1.3 with 1.1 on AWS using terminal? Thank you in advance!

**Comment by david-wb** [comment] 2018-03-01 06:43
Here is a solution that worked for me using the AWS deep learning ami.

1. Add jupyter kernel for your conda environment:
```
python -m ipykernel install --user --name yourenv --display-name "Python (yourenv)"
```
2. Replace the line `tensorflow==1.0.0` in requirements.txt with `tensorflow-gpu==1.0.0`.
3. In your jupyter notebook switch kernels in the menu bar with `kernel->change kernel->Python (yourenv)`.
Good luck!

**Comment by abhiojha8** [comment] 2021-03-30 04:42
Duplicate of #216

**Closed by abhiojha8** 2021-03-30 04:42 UTC
Labels: duplicate
